package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/Activator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-amd64-cygwin/jdk8u301/1513/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Wednesday, June 9, 2021 6:48:02 AM PDT
*/

public interface Activator extends ActivatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Activator
