package org.omg.DynamicAny;


/**
* org/omg/DynamicAny/DynStruct.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-amd64-cygwin/jdk8u301/1513/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Wednesday, June 9, 2021 6:48:02 AM PDT
*/


/**
    * DynStruct objects support the manipulation of IDL struct and exception values.
    * Members of the exceptions are handled in the same way as members of a struct.
    */
public interface DynStruct extends DynStructOperations, org.omg.DynamicAny.DynAny, org.omg.CORBA.portable.IDLEntity 
{
} // interface DynStruct
